### ISSUE TITLE
FileNotFoundException when i'm try run test

### ISSUE THREAD

**Issue by facetoash** [allure-framework/allure-specflow#1]
I am trying to connect Allure to my SpecFlow test project and get exception when i'm try run test:
`OneTimeSetUp: TechTalk.SpecFlow.SpecFlowException : Unable to load plugin: Allure.SpecFlow. Please check http://go.specflow.org/doc-plugins for details.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'Allure.SpecFlow.SpecFlowPlugin' or one of its dependencies. The system cannot find the file specified.`

App.config:
```xml
<?xml` version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
  </configSections>
  <specFlow>
    <generator allowDebugGeneratedFiles="true" />
    <plugins>
      <add name="SpecFlow.Allure" type="Runtime" />
    </plugins>
    <stepAssemblies>
      <stepAssembly assembly="SpecFlow.Allure.SpecFlowPlugin" />
    </stepAssemblies>
  </specFlow>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="TechTalk.SpecFlow" publicKeyToken="0778194805d6db41" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.2.0.0" newVersion="2.2.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```
packages.config:

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="log4net" version="2.0.5" targetFramework="net45" />
  <package id="NUnit" version="3.0.0" targetFramework="net45" />
  <package id="SpecFlow" version="2.2.0-preview20161020" targetFramework="net45" />
  <package id="SpecFlow.Allure" version="1.2.0" targetFramework="net45" />
</packages>
```

What could be the reason?

**Comment by Bakanych** [comment]
Hi, thank you for the feedback.
I mostly tested this adapter for mstest and specrun test runners, but in any case SpecFlow.Allure nuget package libraries should exist in testrunner binary folder. In case of mstest it works automatically as libraries are added as test project references.
Please check your test project binary folder during test execution and let me test it for nunit meanwhile.

**Comment by Bakanych** [comment]
Hi @facetoash,
I've just tested it with nunit 3. It seems to work fine. Please check this example:
https://github.com/allure-framework/allure-specflow/tree/master/SpecFlow.Allure.PackageTests
I used latest release version of Specflow (2.1).

**Comment by facetoash** [comment]
Hi @Bakanych,
Thank you for your example. Now I try again. As results I will write.
